---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
      no-extend-native:
        enabled: false
      global-require:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- test/
- "src/service/web/client/frontend/resources/assets/scripts/uikit.js"
